### ISSUE TITLE
telegram https error

### ISSUE THREAD

**Issue by parsibox** [brozeph/simple-socks#24] opened 2018-05-04 07:36 UTC
hi
what is problem?
```
connected to remote server at 149.154.166.120:443
unable to connect to remote server
{ Error: read ECONNRESET
    at TCP.onread (net.js:659:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
connected to remote server at 149.154.166.120:443
unable to connect to remote server
{ Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:401:12)
    at Socket.<anonymous> (/var/www/simple-socks/lib/socks5.js:260:18)
    at Object.onceWrapper (events.js:275:13)
    at Socket.emit (events.js:187:15)
    at Socket.EventEmitter.emit (domain.js:460:23)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1147:10) code: 'EPIPE' }
```

**Comment by brozeph** [comment] 2018-05-04 15:54
@parsibox - based on the error, it looks like the destination you are trying to reach is down / rejecting inbound connections

**Comment by brozeph** [comment] 2019-01-11 01:24
Closing as unable to reproduce - appears to be related to specific scenario. Will reopen if more details are provided and can be used to debug.

**Closed as completed by brozeph** 2019-01-11 01:24 UTC

**Comment by azhawkes** [comment] 2021-06-30 19:43
@brozeph I'm encountering this as well, but only when running lots of concurrent requests through the proxy (200-400 requests per second). Most likely it's telling the truth and the destination has abruptly closed the connection, as you said. But I also wonder if there might be a race condition and the proxy is trying to reuse an old port too soon or something. Any pointers where I might look to determine which of those it is?

EDIT:

I should also mention that only when proxying do we get the ECONNRESET errors... if I make the same requests from the downstream client directly to the destination, everything seems to work fine.

Thanks for a great lib btw!

**Comment by cco-joshua** [comment] 2021-07-01 13:43
Hi @azhawkes, thank you for this detail! When I read this, I thought about TCP connections… for every request through the proxy, two ports are consumed on the OS where the proxy is hosted. If you are operating the proxy on a dedicated machine, it may help to explore the sysctl configuration of the machine: <https://stackoverflow.com/questions/410616/increasing-the-maximum-number-of-tcp-ip-connections-in-linux>.

I’m not sure this applies to you or not, but if you happen to have the proxy setup in a load balanced scenario, does adding additional machines that act as the proxy to your load balancer help with `ECONNRESET` failures?

**Comment by azhawkes** [comment] 2021-07-01 18:07
@cco-joshua That's a good thought, and thanks for clarifying the number of ports consumed, as I was unsure if SOCKS reuses a persistent connection (tunnel) for multiple HTTPS requests or opens a new one each time.

We've already tuned the networking stack (max files etc) pretty aggressively.

Just now I ran the same test with 2 instances and 9 instances, and found that sharing the load between more instances doesn't seem to have much of an impact. Weirder still, the errors sometimes occur in the first 30 seconds of the test, when only a few thousand requests have been made, so I don't think there's any way we should be exhausting our local ports that early.

I do believe the root cause is something on the destination's end. However, when I run our test with normal Chrome browsers going direct (no proxy), they don't report any errors... the errors only show up when the proxy is involved. Perhaps the browsers automatically retry requests to closed connections when going direct, but not when an error happens in the proxy connection?

Not trying to sign you up for more work, but do you think it's conceptually feasible to make simple-socks more resilient to connection resets like this? Like maybe it could retry the failed connection?
